export const ASSUREURS = [
    { value: '+simple', label: '+Simple' },
    { value: 'kereis', label: 'Kereis' },
    { value: 'a_comme_assure', label: 'A COMME ASSURE' },
    { value: 'abeille_epargne_retraite', label: 'ABEILLE EPARGNE RETRAITE' },
    { value: 'abeille_iard_sante', label: 'ABEILLE IARD & SANTE' },
    { value: 'abeille_retraite_professionnelle', label: 'ABEILLE RETRAITE PROFESSIONNELLE' },
    { value: 'acheel', label: 'ACHEEL' },
    { value: 'acoris_mutuelles', label: 'ACORIS MUTUELLES' },
    { value: 'acta_assurance', label: 'ACTA ASSURANCE' },
    { value: 'acte_iard', label: 'ACTE IARD' },
    { value: 'acte_vie', label: 'ACTE VIE' },
    { value: 'adrea_mutuelle', label: 'ADREA MUTUELLE' },
    { value: 'aesio_mutuelle', label: 'AESIO MUTUELLE' },
    { value: 'aesio_sante', label: 'AESIO SANTE' },
    { value: 'affineo_assur', label: 'AFFINEO ASSUR' },
    { value: 'afi_esca_iard', label: 'AFI ESCA IARD' },
    { value: 'afi_esca', label: 'AFI-ESCA' },
    { value: 'ag2r_prevoyance', label: 'AG2R PREVOYANCE' },
    { value: 'ageas_france', label: 'AGEAS FRANCE' },
    { value: 'agpm_assurances', label: 'AGPM ASSURANCES' },
    { value: 'agpm_vie', label: 'AGPM VIE' },
    { value: 'agri_prevoyance', label: 'AGRI PREVOYANCE' },
    { value: 'aig', label: 'AIG' },
    { value: 'alan', label: 'ALAN' },
    { value: 'albingia', label: 'ALBINGIA' },
    { value: 'alliance_mutualistes_transport', label: 'ALLIANCE DES MUTUALISTES DU TRANSPORT ET DU SECTEUR SOCIAL' },
    { value: 'allianz_iard', label: 'ALLIANZ IARD' },
    { value: 'allianz_retraite', label: 'ALLIANZ RETRAITE' },
    { value: 'allianz_vie', label: 'ALLIANZ VIE' },
    { value: 'alptis_assurances', label: 'ALPTIS ASSURANCES' },
    { value: 'altaprofit', label: 'ALTAPROFIT' },
    { value: 'alteis_mutuelles', label: 'ALTEIS MUTUELLES' },
    { value: 'altima_assurances', label: 'ALTIMA ASSURANCES' },
    { value: 'amaguiz', label: 'AMAGUIZ' },
    { value: 'amellis_mutuelles', label: 'AMELLIS MUTUELLES' },
    { value: 'anips', label: 'ANIPS' },
    { value: 'antarius', label: 'ANTARIUS' },
    { value: 'aon_france', label: 'AON FRANCE' },
    { value: 'apgis', label: 'APGIS' },
    { value: 'apicil_epargne', label: 'APICIL EPARGNE' },
    { value: 'apicil_epargne_retraite', label: 'APICIL EPARGNE RETRAITE' },
    { value: 'apicil_mutuelle', label: 'APICIL MUTUELLE' },
    { value: 'apicil_prevoyance', label: 'APICIL PREVOYANCE' },
    { value: 'apivia_macif_mutuelle', label: 'APIVIA MACIF MUTUELLE' },
    { value: 'april', label: 'APRIL' },
    { value: 'areas_dommages', label: 'AREAS DOMMAGES' },
    { value: 'areas_vie', label: 'AREAS VIE' },
    { value: 'arial_cnp_assurances', label: 'ARIAL CNP ASSURANCES' },
    { value: 'arpege_prevoyance', label: 'ARPEGE PREVOYANCE' },
    { value: 'association_generale_medecins_france', label: 'ASSOCIATION GENERALE DES MEDECINS DE FRANCE PREVOYANCE' },
    { value: 'association_generale_mutuelles', label: 'ASSOCIATION GENERALE DES MUTUELLES' },
    { value: 'assu_2000', label: 'ASSU 2000' },
    { value: 'assur_travel', label: 'ASSUR TRAVEL' },
    { value: 'assurance_conseil_defense', label: 'ASSURANCE CONSEIL DEFENSE ET RECOURS' },
    { value: 'assurance_mutuelle_illkirch', label: 'ASSURANCE MUTUELLE D ILLKIRCH GRAFFENSTADEN' },
    { value: 'assurance_mutuelle_outremer', label: 'ASSURANCE MUTUELLE D OUTREMER' },
    { value: 'assurance_mutuelle_fonctionnaires', label: 'ASSURANCE MUTUELLE DES FONCTIONNAIRES ET ASSIMILES DES COMPTABLES PUBLICS ET DES AGENTS COMPTABLES' },
    { value: 'mutuelle_des_motards', label: 'MUTUELLE DES MOTARDS' },
    { value: 'assurance_mutuelle_val_de_saone', label: 'ASSURANCE MUTUELLE VAL DE SAONE BEAUJOLAIS' },
    { value: 'assurances_credit_mutuel_iard', label: 'ASSURANCES DU CREDIT MUTUEL IARD - INCENDIE - ACCIDENTS - RISQUES DIVERS - S.A.' },
    { value: 'assurances_credit_mutuel_vie', label: 'ASSURANCES DU CREDIT MUTUEL VIE' },
    { value: 'assurances_credit_mutuel_vie_sa', label: 'ASSURANCES DU CREDIT MUTUEL VIE SA' },
    { value: 'assurances_mutuelles_conservateur', label: 'ASSURANCES MUTUELLES LE CONSERVATEUR' },
    { value: 'assurances_mutuelles_france', label: 'ASSURANCES MUTUELLES DE FRANCE' },
    { value: 'assurances_mutuelles_picardie', label: 'ASSURANCES MUTUELLES DE PICARDIE' },
    { value: 'assured_guaranty_europe', label: 'ASSURED GUARANTY EUROPE SA' },
    { value: 'assurima', label: 'ASSURIMA' },
    { value: 'assurly', label: 'ASSURLY' },
    { value: 'assurone', label: 'ASSURONE' },
    { value: 'assur_opoil', label: 'ASSUR OPOIL' },
    { value: 'assu_vie', label: 'ASSU-VIE' },
    { value: 'aubeane_mutuelle_france', label: 'AUBEANE MUTUELLE DE FRANCE' },
    { value: 'audiens_sante_prevoyance', label: 'AUDIENS SANTE-PREVOYANCE' },
    { value: 'auxia', label: 'AUXIA' },
    { value: 'avanssur', label: 'AVANSSUR' },
    { value: 'avenir_mutuel_professions_liberales', label: 'AVENIR MUTUEL DES PROFESSIONS LIBERALES ET INDEPENDANTES' },
    { value: 'avenir_mutuelle', label: 'AVENIR MUTUELLE' },
    { value: 'avenir_sante', label: 'AVENIR SANTE' },
    { value: 'avenir_sante_mutuelle', label: 'AVENIR SANTE MUTUELLE' },
    { value: 'aviva_vie', label: 'AVIVA VIE' },
    { value: 'awp_health_life', label: 'AWP HEALTH & LIFE' },
    { value: 'awp_pc', label: 'AWP P&C' },
    { value: 'axa_assurances_iard_mutuelle', label: 'AXA ASSURANCES IARD MUTUELLE' },
    { value: 'axa_assurances_vie_mutuelle', label: 'AXA ASSURANCES VIE MUTUELLE' },
    { value: 'axa_assurcredit', label: 'AXA ASSURCREDIT' },
    { value: 'axa_france_iard', label: 'AXA FRANCE IARD' },
    { value: 'axa_france_vie', label: 'AXA FRANCE VIE' },
    { value: 'axa_global_re', label: 'AXA GLOBAL RE' },
    { value: 'axa_retraite_entreprise', label: 'AXA RETRAITE ENTREPRISE' },
    { value: 'axa_sante_collective', label: 'AXA SANTE COLLECTIVE' },
    { value: 'axa_sante_collective_iard', label: 'AXA SANTE COLLECTIVE IARD' },
    { value: 'axa_sante_collective_vie', label: 'AXA SANTE COLLECTIVE VIE' },
    { value: 'axa_vie', label: 'AXA VIE' },
    { value: 'axa_vie_pension', label: 'AXA VIE PENSION' },
    { value: 'axa_vie_prevoyance', label: 'AXA VIE PREVOYANCE' },
    { value: 'axime', label: 'AXIME' },
    { value: 'azur_assurances', label: 'AZUR ASSURANCES' },
    { value: 'baloo', label: 'BALOO' },
    { value: 'banque_postale_assurances_iard', label: 'BANQUE POSTALE ASSURANCES IARD' },
    { value: 'banque_postale_assurances_sante', label: 'BANQUE POSTALE ASSURANCES SANTE' },
    { value: 'banque_postale_prevoyance', label: 'BANQUE POSTALE PREVOYANCE' },
    { value: 'banque_postale_vie', label: 'BANQUE POSTALE VIE' },
    { value: 'bayard_vie', label: 'BAYARD VIE' },
    { value: 'bcac', label: 'BCAC' },
    { value: 'bcpe_vie', label: 'BCPE VIE' },
    { value: 'beazley', label: 'BEAZLEY' },
    { value: 'bergamo', label: 'BERGAMO' },
    { value: 'bernard_assurances', label: 'BERNARD ASSURANCES' },
    { value: 'bfsa', label: 'BFSA' },
    { value: 'billon_assurances', label: 'BILLON ASSURANCES' },
    { value: 'bnp_paribas_cardif', label: 'BNP PARIBAS CARDIF' },
    { value: 'bnp_paribas_cardif_iard', label: 'BNP PARIBAS CARDIF IARD' },
    { value: 'bnp_paribas_cardif_vie', label: 'BNP PARIBAS CARDIF VIE' },
    { value: 'bnp_paribas_epargne_retraite', label: 'BNP PARIBAS EPARGNE RETRAITE' },
    { value: 'bourbon', label: 'BOURBON' },
    { value: 'bpce_assurances', label: 'BPCE ASSURANCES' },
    { value: 'bpce_iard', label: 'BPCE IARD' },
    { value: 'bpce_vie', label: 'BPCE VIE' },
    { value: 'brancherie_assurances', label: 'BRANCHERIE ASSURANCES' },
    { value: 'brancherie_iard', label: 'BRANCHERIE IARD' },
    { value: 'brancherie_vie', label: 'BRANCHERIE VIE' },
    { value: 'branches_assurances', label: 'BRANCHES ASSURANCES' },
    { value: 'btp_prevoyance', label: 'BTP PREVOYANCE' },
    { value: 'btp_sante', label: 'BTP SANTE' },
    { value: 'btp_vie', label: 'BTP VIE' },
    { value: 'bureau_central_tarification', label: 'BUREAU CENTRAL DE TARIFICATION' },
    { value: 'cabinet_assurances_gayraud', label: 'CABINET ASSURANCES GAYRAUD' },
    { value: 'cabinet_beneat', label: 'CABINET BENEAT' },
    { value: 'cabinet_boyer', label: 'CABINET BOYER' },
    { value: 'cabinet_cabanes', label: 'CABINET CABANES' },
    { value: 'cabinet_camin', label: 'CABINET CAMIN' },
    { value: 'cabinet_langlades', label: "CABINET D'ASSURANCES LANGLADE" },
    { value: 'cabinet_de_rohan', label: 'CABINET DE ROHAN' },
    { value: 'cabinet_desrousseaux', label: 'CABINET DESROUSSEAUX' },
    { value: 'cabinet_dubois', label: 'CABINET DUBOIS' },
    { value: 'cabinet_durand', label: 'CABINET DURAND' },
    { value: 'cabinet_gourbeyre', label: 'CABINET GOURBEYRE' },
    { value: 'cabinet_langlades', label: 'CABINET LANGLADE' },
    { value: 'cabinet_lecorps', label: 'CABINET LECORPS' },
    { value: 'cabinet_michel', label: 'CABINET MICHEL' },
    { value: 'cabinet_ory', label: 'CABINET ORY' },
    { value: 'cabinet_paulet', label: 'CABINET PAULET' },
    { value: 'cabinet_pont', label: 'CABINET PONT' },
    { value: 'cabinet_remond', label: 'CABINET REMOND' },
    { value: 'cabinet_vivier', label: 'CABINET VIVIER' },
    { value: 'caci_life', label: 'CACI LIFE' },
    { value: 'caci_non_life', label: 'CACI NON LIFE' },
    { value: 'camacte', label: 'CAMACTE' },
    { value: 'camb', label: 'CAMB' },
    { value: 'cap_assurances', label: 'CAP ASSURANCES' },
    { value: 'cap_avenir', label: 'CAP AVENIR' },
    { value: 'cap_finances', label: 'CAP FINANCES' },
    { value: 'cap_mutuelles', label: 'CAP MUTUELLES' },
    { value: 'cap_sante', label: 'CAP SANTE' },
    { value: 'cap_vie', label: 'CAP VIE' },
    { value: 'capital_assurances', label: 'CAPITAL ASSURANCES' },
    { value: 'capma_capmi', label: 'CAPMA & CAPMI' },
    { value: 'capvia', label: 'CAPVIA' },
    { value: 'carac', label: 'CARAC' },
    { value: 'carte_blanche_partenaires', label: 'CARTE BLANCHE PARTENAIRES' },
    { value: 'carte_vie', label: 'CARTE VIE' },
    { value: 'casden_prevoyance', label: 'CASDEN PREVOYANCE' },
    { value: 'ccmo_mutuelle', label: 'CCMO MUTUELLE' },
    { value: 'ccra', label: 'CCRA' },
    { value: 'ccrcs', label: 'CCRCS' },
    { value: 'ccrv', label: 'CCRV' },
    { value: 'cdg_prevoyance', label: 'CDG PREVOYANCE' },
    { value: 'cegema', label: 'CEGEMA' },
    { value: 'cegedim', label: 'CEGEDIM' },
    { value: 'celtis_assurances', label: 'CELTIS ASSURANCES' },
    { value: 'cfdp_assurances', label: 'CFDP ASSURANCES' },
    { value: 'cfi_assurances', label: 'CFI ASSURANCES' },
    { value: 'cgpa', label: 'CGPA' },
    { value: 'challenger_assurances', label: 'CHALLENGER ASSURANCES' },
    { value: 'chapka_assurances', label: 'CHAPKA ASSURANCES' },
    { value: 'chubb', label: 'CHUBB' },
    { value: 'chubb_europe', label: 'CHUBB EUROPE' },
    { value: 'cic_assurances', label: 'CIC ASSURANCES' },
    { value: 'cic_iard', label: 'CIC IARD' },
    { value: 'cic_prevoyance', label: 'CIC PREVOYANCE' },
    { value: 'cic_vie', label: 'CIC VIE' },
    { value: 'cigna', label: 'CIGNA' },
    { value: 'cimut', label: 'CIMUT' },
    { value: 'ciprev', label: 'CIPREV' },
    { value: 'ciprev_retraite', label: 'CIPREV RETRAITE' },
    { value: 'ciprev_vie', label: 'CIPREV VIE' },
    { value: 'ciprevie', label: 'CIPREVIE' },
    { value: 'cis_caraibes', label: 'CIS CARAÏBES' },
    { value: 'cisame', label: 'CISAME' },
    { value: 'citrix', label: 'CITRIX' },
    { value: 'civis', label: 'CIVIS' },
    { value: 'clean_assur', label: 'CLEAN ASSUR' },
    { value: 'clear_assur', label: 'CLEAR ASSUR' },
    { value: 'cnm_prevoyance_sante', label: 'CNM PREVOYANCE SANTE' },
    { value: 'cnm_sante', label: 'CNM SANTE' },
    { value: 'cnm_vie', label: 'CNM VIE' },
    { value: 'cnp_assurances', label: 'CNP ASSURANCES' },
    { value: 'cnp_prevoyance', label: 'CNP PREVOYANCE' },
    { value: 'cnp_retraite', label: 'CNP RETRAITE' },
    { value: 'cnp_vie', label: 'CNP VIE' },
    { value: 'cnp_vie_epargne', label: 'CNP VIE EPARGNE' },
    { value: 'cobaci', label: 'COBACI' },
    { value: 'collecteam', label: 'COLLECTEAM' },
    { value: 'colyssee_patrimoine', label: 'COLYSEE PATRIMOINE' },
    { value: 'coma', label: 'COMA' },
    { value: 'comatrassur', label: 'COMATRASSUR' },
    { value: 'complementaire_retraite_hospitaliers', label: 'COMPLEMENTAIRE RETRAITE DES HOSPITALIERS' },
    { value: 'complementaire_sante_groupe_lourmel', label: 'COMPLEMENTAIRE SANTE GROUPE LOURMEL' },
    { value: 'complementaire_sante_lourmel', label: 'COMPLEMENTAIRE SANTE LOURMEL' },
    { value: 'compagnie_agents_voyages', label: 'COMPAGNIE DES AGENTS DE VOYAGES' },
    { value: 'compagnie_europeenne_garanties', label: 'COMPAGNIE EUROPEENNE DE GARANTIES ET CAUTIONS' },
    { value: 'compagnie_europeenne_prevoyance', label: 'COMPAGNIE EUROPEENNE PREVOYANCE' },
    { value: 'compagnie_generale_assurances_vie', label: 'COMPAGNIE GENERALE D ASSURANCES VIE' },
    { value: 'compagnie_generale_assurances_vie_cgav', label: 'COMPAGNIE GENERALE D ASSURANCES VIE CGAV' },
    { value: 'compagnie_generale_prevoyance', label: 'COMPAGNIE GENERALE DE PREVOYANCE' },
    { value: 'compagnie_inter_mutuelle_assurances', label: 'COMPAGNIE INTER MUTUELLE D ASSURANCES' },
    { value: 'compagnie_mutuelle_reassurance', label: 'COMPAGNIE MUTUELLE DE REASSURANCE' },
    { value: 'compagnie_mutuelle_assurance_batiment', label: 'COMPAGNIE MUTUELLE D ASSURANCE DU BATIMENT ET DES TRAVAUX PUBLICS' },
    { value: 'compagnie_mutuelle_assurance_vie', label: 'COMPAGNIE MUTUELLE D ASSURANCE SUR LA VIE' },
    { value: 'compagnie_suisse_reassurance', label: 'COMPAGNIE SUISSE DE REASSURANCE' },
    { value: 'compass_group', label: 'COMPASS GROUP' },
    { value: 'comptoir_general_assurances', label: 'COMPTOIR GENERAL D ASSURANCES' },
    { value: 'comptoir_general_assurance', label: 'COMPTOIR GENERAL DE L ASSURANCE' },
    { value: 'concorde_assurances', label: 'CONCORDE ASSURANCES' },
    { value: 'confiance_sante', label: 'CONFIANCE SANTE' },
    { value: 'confort_assurance', label: 'CONFORT ASSURANCE' },
    { value: 'conseil_assurances', label: 'CONSEIL ASSURANCES' },
    { value: 'conseil_sante', label: 'CONSEIL SANTE' },
    { value: 'conseil_vie', label: 'CONSEIL VIE' },
    { value: 'convivencia', label: 'CONVIVENCIA' },
    { value: 'cooperative_assurance', label: 'COOPERATIVE D ASSURANCE' },
    { value: 'cooperative_assurance_mutuelle', label: 'COOPERATIVE D ASSURANCE MUTUELLE' },
    { value: 'corum_epargne', label: 'CORUM L EPARGNE' },
    { value: 'coste_et_associes', label: 'COSTE & ASSOCIES' },
    { value: 'coversure', label: 'COVERSURE' },
    { value: 'cpms', label: 'CPMS' },
    { value: 'credit_agricole_assurances', label: 'CREDIT AGRICOLE ASSURANCES' },
    { value: 'credit_agricole_cib', label: 'CREDIT AGRICOLE CIB' },
    { value: 'credit_agricole_epargne_retraite', label: 'CREDIT AGRICOLE EPARGNE RETRAITE' },
    { value: 'credit_agricole_iard', label: 'CREDIT AGRICOLE IARD' },
    { value: 'credit_agricole_prevoyance', label: 'CREDIT AGRICOLE PREVOYANCE' },
    { value: 'credit_agricole_sante', label: 'CREDIT AGRICOLE SANTE' },
    { value: 'credit_agricole_vie', label: 'CREDIT AGRICOLE VIE' },
    { value: 'credit_mutuel_assurance_sante', label: 'CREDIT MUTUEL ASSURANCE SANTE' },
    { value: 'credit_mutuel_epargne_retraite', label: 'CREDIT MUTUEL EPARGNE RETRAITE' },
    { value: 'credit_mutuel_iard', label: 'CREDIT MUTUEL IARD' },
    { value: 'credit_mutuel_prevoyance', label: 'CREDIT MUTUEL PREVOYANCE' },
    { value: 'credit_mutuel_vie', label: 'CREDIT MUTUEL VIE' },
    { value: 'crystal_assurances', label: 'CRYSTAL ASSURANCES' },
    { value: 'csf', label: 'CSF' },
    { value: 'cumar', label: 'CUMAR' },
    { value: 'curef', label: 'CUREF' },
    { value: 'curef_prevoyance', label: 'CUREF PREVOYANCE' },
    { value: 'curef_vie', label: 'CUREF VIE' },
    { value: 'curefep', label: 'CUREFEP' },
    { value: 'cyrial_assurances', label: 'CYRIAL ASSURANCES' },
    { value: 'dassault_assurances', label: 'DASSAULT ASSURANCES' },
    { value: 'dassault_iard', label: 'DASSAULT IARD' },
    { value: 'dassault_vie', label: 'DASSAULT VIE' },
    { value: 'davaine_assurances', label: 'DAVAINE ASSURANCES' },
    { value: 'davaine_vie', label: 'DAVAINE VIE' },
    { value: 'decuyper_assurances', label: 'DECUYPER ASSURANCES' },
    { value: 'delta_assurances', label: 'DELTA ASSURANCES' },
    { value: 'depreux_assurances', label: 'DEPREUX ASSURANCES' },
    { value: 'derichebourg_assurances', label: 'DERICHEBOURG ASSURANCES' },
    { value: 'deslauriers', label: 'DESLAURIERS' },
    { value: 'devk', label: 'DEVK' },
    { value: 'diaf', label: 'DIAF' },
    { value: 'diot', label: 'DIOT' },
    { value: 'dip', label: 'DIP' },
    { value: 'disponis', label: 'DISPONIS' },
    { value: 'divial', label: 'DIVIAL' },
    { value: 'dkv', label: 'DKV' },
    { value: 'docteur_assurances', label: 'DOCTEUR ASSURANCES' },
    { value: 'docteur_prevoyance', label: 'DOCTEUR PREVOYANCE' },
    { value: 'docteur_vie', label: 'DOCTEUR VIE' },
    { value: 'domisante', label: 'DOMISANTE' },
    { value: 'dorsia', label: 'DORSIA' },
    { value: 'drouot_assurances', label: 'DROUOT ASSURANCES' },
    { value: 'drouot_vie', label: 'DROUOT VIE' },
    { value: 'duclos_assurances', label: 'DUCLOS ASSURANCES' },
    { value: 'ducournau_assurances', label: 'DUCOURNAU ASSURANCES' },
    { value: 'dumas_assurances', label: 'DUMAS ASSURANCES' },
    { value: 'durand_assurances', label: 'DURAND ASSURANCES' },
    { value: 'eca', label: 'ECA' },
    { value: 'eca_iard', label: 'ECA IARD' },
    { value: 'eca_vie', label: 'ECA VIE' },
    { value: 'ecc', label: 'ECC' },
    { value: 'ecole_de_conduite', label: 'ECOLE DE CONDUITE' },
    { value: 'ecureuil_vie', label: 'ECUREUIL VIE' },
    { value: 'eden_assurances', label: 'EDEN ASSURANCES' },
    { value: 'edf_assurances', label: 'EDF ASSURANCES' },
    { value: 'edf_iard', label: 'EDF IARD' },
    { value: 'edf_vie', label: 'EDF VIE' },
    { value: 'edr_assurances', label: 'EDR ASSURANCES' },
    { value: 'eig', label: 'EIG' },
    { value: 'eligis', label: 'ELIGIS' },
    { value: 'eligis_prevoyance', label: 'ELIGIS PREVOYANCE' },
    { value: 'eligis_vie', label: 'ELIGIS VIE' },
    { value: 'elips_life', label: 'ELIPS LIFE' },
    { value: 'elvia', label: 'ELVIA' },
    { value: 'emoa_mutuelle', label: 'EMOA MUTUELLE' },
    { value: 'emprunteur_assurances', label: 'EMPRUNTEUR ASSURANCES' },
    { value: 'enim', label: 'ENIM' },
    { value: 'entis', label: 'ENTIS' },
    { value: 'entoria', label: 'ENTORIA' },
    { value: 'entoria_iard', label: 'ENTORIA IARD' },
    { value: 'entoria_vie', label: 'ENTORIA VIE' },
    { value: 'entrenous_assurances', label: 'ENTRENOUS ASSURANCES' },
    { value: 'epsens', label: 'EPSENS' },
    { value: 'epson_assurances', label: 'EPSON ASSURANCES' },
    { value: 'epsyl', label: 'EPSYL' },
    { value: 'equadis', label: 'EQUADIS' },
    { value: 'equatio', label: 'EQUATIO' },
    { value: 'equity', label: 'EQUITY' },
    { value: 'equity_life', label: 'EQUITY LIFE' },
    { value: 'equity_vie', label: 'EQUITY VIE' },
    { value: 'ergo', label: 'ERGO' },
    { value: 'ergo_prevoyance', label: 'ERGO PREVOYANCE' },
    { value: 'ergo_vie', label: 'ERGO VIE' },
    { value: 'ergon', label: 'ERGON' },
    { value: 'eriva', label: 'ERIVA' },
    { value: 'esn', label: 'ESN' },
    { value: 'espavie', label: 'ESPAVIE' },
    { value: 'esprit_libre', label: 'ESPRIT LIBRE' },
    { value: 'esprit_sante', label: 'ESPRIT SANTE' },
    { value: 'essentielle_sante', label: 'ESSENTIELLE SANTE' },
    { value: 'est_mutualite', label: 'EST MUTUALITE' },
    { value: 'etasunis', label: 'ETASUNIS' },
    { value: 'europ_assistance', label: 'EUROP ASSISTANCE' },
    { value: 'europ_assistance_vie', label: 'EUROP ASSISTANCE VIE' },
    { value: 'europavie', label: 'EUROPAVIE' },
    { value: 'europazur', label: 'EUROPAZUR' },
    { value: 'europeenne_assurance_sante', label: 'EUROPEENNE D ASSURANCE SANTE' },
    { value: 'europeenne_prevoyance', label: 'EUROPEENNE DE PREVOYANCE' },
    { value: 'europeenne_epargne', label: 'EUROPEENNE D EPARGNE' },
    { value: 'europeenne_vie', label: 'EUROPEENNE VIE' },
    { value: 'europvie', label: 'EUROPVIE' },
    { value: 'eurovie', label: 'EUROVIE' },
    { value: 'evolis', label: 'EVOLIS' },
    { value: 'excel', label: 'EXCEL' },
    { value: 'expert_sante', label: 'EXPERT SANTE' },
    { value: 'expert_vie', label: 'EXPERT VIE' },
    { value: 'express_vie', label: 'EXPRESS VIE' },
    { value: 'expro', label: 'EXPRO' },
    { value: 'fabbro_assurances', label: 'FABBRO ASSURANCES' },
    { value: 'famille_assurances', label: 'FAMILLE ASSURANCES' },
    { value: 'fami_vie', label: 'FAMI-VIE' },
    { value: 'far', label: 'FAR' },
    { value: 'far_prevoyance', label: 'FAR PREVOYANCE' },
    { value: 'far_sante', label: 'FAR SANTE' },
    { value: 'far_vie', label: 'FAR VIE' },
    { value: 'fargues_assurances', label: 'FARGUES ASSURANCES' },
    { value: 'farm_assurances', label: 'FARM ASSURANCES' },
    { value: 'favreau_assurances', label: 'FAVREAU ASSURANCES' },
    { value: 'fcn_assurances', label: 'FCN ASSURANCES' },
    { value: 'fehap', label: 'FEHAP' },
    { value: 'fehap_prevoyance', label: 'FEHAP PREVOYANCE' },
    { value: 'fehap_sante', label: 'FEHAP SANTE' },
    { value: 'fehap_vie', label: 'FEHAP VIE' },
    { value: 'fehapep', label: 'FEHAPEP' },
    { value: 'fenet_assurances', label: 'FENET ASSURANCES' },
    { value: 'ferrand_assurances', label: 'FERRAND ASSURANCES' },
    { value: 'ffsa', label: 'FFSA' },
    { value: 'fg_assurances', label: 'FG ASSURANCES' },
    { value: 'fga', label: 'FGA' },
    { value: 'fga_prevoyance', label: 'FGA PREVOYANCE' },
    { value: 'fga_vie', label: 'FGA VIE' },
    { value: 'fidelia', label: 'FIDELIA' },
    { value: 'fidl', label: 'FIDL' },
    { value: 'fiducial', label: 'FIDUCIAL' },
    { value: 'finaxy_group', label: 'FINAXY GROUP' },
    { value: 'finegan', label: 'FINEGAN' },
    { value: 'finsevie', label: 'FINSEVIE' },
    { value: 'fiprev', label: 'FIPREV' },
    { value: 'fisassur', label: 'FISASSUR' },
    { value: 'flandre_assurances', label: 'FLANDRE ASSURANCES' },
    { value: 'flavia', label: 'FLAVIA' },
    { value: 'flavia_vie', label: 'FLAVIA VIE' },
    { value: 'fmg_assurances', label: 'FMG ASSURANCES' },
    { value: 'fmp_assurances', label: 'FMP ASSURANCES' },
    { value: 'fms', label: 'FMS' },
    { value: 'fms_sante', label: 'FMS SANTE' },
    { value: 'fms_vie', label: 'FMS VIE' },
    { value: 'fmv', label: 'FMV' },
    { value: 'fnaim_assurances', label: 'FNAIM ASSURANCES' },
    { value: 'fnath', label: 'FNATH' },
    { value: 'fnath_prevoyance', label: 'FNATH PREVOYANCE' },
    { value: 'fnath_sante', label: 'FNATH SANTE' },
    { value: 'fnath_vie', label: 'FNATH VIE' },
    { value: 'foliateam', label: 'FOLIATEAM' },
    { value: 'fondation_april', label: 'FONDATION APRIL' },
    { value: 'fongepar', label: 'FONGEPAR' },
    { value: 'forges_assurances', label: 'FORGES ASSURANCES' },
    { value: 'formidable_assurances', label: 'FORMIDABLE ASSURANCES' },
    { value: 'forum_assurances', label: 'FORUM ASSURANCES' },
    { value: 'fossard_assurances', label: 'FOSSARD ASSURANCES' },
    { value: 'foucher_assurances', label: 'FOUCHER ASSURANCES' },
    { value: 'fouillet_assurances', label: 'FOUILLET ASSURANCES' },
    { value: 'fourcade_assurances', label: 'FOURCADE ASSURANCES' },
    { value: 'france_assureur', label: 'FRANCE ASSUREUR' },
    { value: 'france_assureurs', label: 'FRANCE ASSUREURS' },
    { value: 'france_mutualite', label: 'FRANCE MUTUALITE' },
    { value: 'france_prevoyance', label: 'FRANCE PREVOYANCE' },
    { value: 'france_sante', label: 'FRANCE SANTE' },
    { value: 'france_vie', label: 'FRANCE VIE' },
    { value: 'franceepargne', label: 'FRANCEEPARGNE' },
    { value: 'francelia', label: 'FRANCELIA' },
    { value: 'francelia_vie', label: 'FRANCELIA VIE' },
    { value: 'franchini_assurances', label: 'FRANCHINI ASSURANCES' },
    { value: 'frandassur', label: 'FRANDASSUR' },
    { value: 'franfinance', label: 'FRANFINANCE' },
    { value: 'franfinance_prevoyance', label: 'FRANFINANCE PREVOYANCE' },
    { value: 'franfinance_sante', label: 'FRANFINANCE SANTE' },
    { value: 'franfinance_vie', label: 'FRANFINANCE VIE' },
    { value: 'franklin_assurances', label: 'FRANKLIN ASSURANCES' },
    { value: 'fraternelle_prevoyance', label: 'FRATERNELLE DE PREVOYANCE' },
    { value: 'fraternelle_sante', label: 'FRATERNELLE SANTE' },
    { value: 'fraternelle_vie', label: 'FRATERNELLE VIE' },
    { value: 'fraternite', label: 'FRATERNITE' },
    { value: 'fraternite_sante', label: 'FRATERNITE SANTE' },
    { value: 'fraternite_vie', label: 'FRATERNITE VIE' },
    { value: 'frederic_assurances', label: 'FREDERIC ASSURANCES' },
    { value: 'fremantel_assurances', label: 'FREMANTEL ASSURANCES' },
    { value: 'fri_assurances', label: 'FRI ASSURANCES' },
    { value: 'frontalis', label: 'FRONTALIS' },
    { value: 'fse', label: 'FSE' },
    { value: 'futura_assurances', label: 'FUTURA ASSURANCES' },
    { value: 'futuria', label: 'FUTURIA' },
    { value: 'futuria_sante', label: 'FUTURIA SANTE' },
    { value: 'futuria_vie', label: 'FUTURIA VIE' },
    { value: 'futurprev', label: 'FUTURPREV' },
    { value: 'ga_conseil', label: 'GA CONSEIL' },
    { value: 'ga_prevoyance', label: 'GA PREVOYANCE' },
    { value: 'ga_sante', label: 'GA SANTE' },
    { value: 'ga_vie', label: 'GA VIE' },
    { value: 'gac', label: 'GAC' },
    { value: 'gac_assurances', label: 'GAC ASSURANCES' },
    { value: 'galian', label: 'GALIAN' },
    { value: 'galilee_vie', label: 'GALILEE VIE' },
    { value: 'gallian_vie', label: 'GALLIAN VIE' },
    { value: 'gan_assurances', label: 'GAN ASSURANCES' },
    { value: 'gan_assurances_vie', label: 'GAN ASSURANCES VIE' },
    { value: 'gan_epargne', label: 'GAN EPARGNE' },
    { value: 'gan_epargne_retraite', label: 'GAN EPARGNE RETRAITE' },
    { value: 'gan_iard', label: 'GAN IARD' },
    { value: 'gan_prevoyance', label: 'GAN PREVOYANCE' },
    { value: 'gan_sante', label: 'GAN SANTE' },
    { value: 'gan_vie', label: 'GAN VIE' },
    { value: 'garance', label: 'GARANCE' },
    { value: 'gardien_assurances', label: 'GARDIEN ASSURANCES' },
    { value: 'garp', label: 'GARP' },
    { value: 'gasnier_assurances', label: 'GASNIER ASSURANCES' },
    { value: 'gassier_assurances', label: 'GASSIER ASSURANCES' },
    { value: 'gaston_assurances', label: 'GASTON ASSURANCES' },
    { value: 'gaudin_assurances', label: 'GAUDIN ASSURANCES' },
    { value: 'gautier_assurances', label: 'GAUTIER ASSURANCES' },
    { value: 'gauvin_assurances', label: 'GAUVIN ASSURANCES' },
    { value: 'gb_assurances', label: 'GB ASSURANCES' },
    { value: 'gc_prevoyance', label: 'GC PREVOYANCE' },
    { value: 'gc_sante', label: 'GC SANTE' },
    { value: 'gc_vie', label: 'GC VIE' },
    { value: 'gda_assurances', label: 'GDA ASSURANCES' },
    { value: 'gdm', label: 'GDM' },
    { value: 'gdm_sante', label: 'GDM SANTE' },
    { value: 'gdm_vie', label: 'GDM VIE' },
    { value: 'generali_france', label: 'GENERALI FRANCE' },
    { value: 'generali_iard', label: 'GENERALI IARD' },
    { value: 'generali_prevoyance', label: 'GENERALI PREVOYANCE' },
    { value: 'generali_sante', label: 'GENERALI SANTE' },
    { value: 'generali_vie', label: 'GENERALI VIE' },
    { value: 'generation', label: 'GENERATION' },
    { value: 'generation_vie', label: 'GENERATION VIE' },
    { value: 'geniris', label: 'GENIRIS' },
    { value: 'geoffroy_assurances', label: 'GEOFFROY ASSURANCES' },
    { value: 'gerantie_assurances', label: 'GERANTIE ASSURANCES' },
    { value: 'geric', label: 'GERIC' },
    { value: 'gerin', label: 'GERIN' },
    { value: 'gestelia', label: 'GESTELIA' },
    { value: 'gestelia_assurances', label: 'GESTELIA ASSURANCES' },
    { value: 'gestelia_vie', label: 'GESTELIA VIE' },
    { value: 'gestion_donnees', label: 'GESTION DES DONNEES' },
    { value: 'gestinea', label: 'GESTINEA' },
    { value: 'gestinea_prevoyance', label: 'GESTINEA PREVOYANCE' },
    { value: 'gestinea_sante', label: 'GESTINEA SANTE' },
    { value: 'gestinea_vie', label: 'GESTINEA VIE' },
    { value: 'gestivie', label: 'GESTIVIE' },
    { value: 'gf_assurances', label: 'GF ASSURANCES' },
    { value: 'gharib_assurances', label: 'GHARIB ASSURANCES' },
    { value: 'gia', label: 'GIA' },
    { value: 'gie_agpm', label: 'GIE AGPM' },
    { value: 'gie_april', label: 'GIE APRIL' },
    { value: 'gie_axa', label: 'GIE AXA' },
    { value: 'gie_bnp', label: 'GIE BNP' },
    { value: 'gie_carte_blanche', label: 'GIE CARTE BLANCHE' },
    { value: 'gie_covea', label: 'GIE COVEA' },
    { value: 'gie_generali', label: 'GIE GENERALI' },
    { value: 'gie_groupama', label: 'GIE GROUPAMA' },
    { value: 'gie_groupavie', label: 'GIE GROUPAVIE' },
    { value: 'gie_harmonie', label: 'GIE HARMONIE' },
    { value: 'gie_lourmel', label: 'GIE LOURMEL' },
    { value: 'gie_malakoff', label: 'GIE MALAKOFF' },
    { value: 'gie_mutuelles', label: 'GIE MUTUELLES' },
    { value: 'gie_swiss_life', label: 'GIE SWISS LIFE' },
    { value: 'gie_vie', label: 'GIE VIE' },
    { value: 'gif', label: 'GIF' },
    { value: 'gif_vie', label: 'GIF VIE' },
    { value: 'gilles_assurances', label: 'GILLES ASSURANCES' },
    { value: 'gisors_assurances', label: 'GISORS ASSURANCES' },
    { value: 'gix_assurances', label: 'GIX ASSURANCES' },
    { value: 'globale_assurances', label: 'GLOBALE ASSURANCES' },
    { value: 'globale_vie', label: 'GLOBALE VIE' },
    { value: 'gmf', label: 'GMF' },
    { value: 'gmf_assurances', label: 'GMF ASSURANCES' },
    { value: 'gmf_epargne', label: 'GMF EPARGNE' },
    { value: 'gmf_epargne_retraite', label: 'GMF EPARGNE RETRAITE' },
    { value: 'gmf_iard', label: 'GMF IARD' },
    { value: 'gmf_prevoyance', label: 'GMF PREVOYANCE' },
    { value: 'gmf_sante', label: 'GMF SANTE' },
    { value: 'gmf_vie', label: 'GMF VIE' },
    { value: 'gmpa', label: 'GMPA' },
    { value: 'gmpa_prevoyance', label: 'GMPA PREVOYANCE' },
    { value: 'gmpa_sante', label: 'GMPA SANTE' },
    { value: 'gmpa_vie', label: 'GMPA VIE' },
    { value: 'gms', label: 'GMS' },
    { value: 'gms_prevoyance', label: 'GMS PREVOYANCE' },
    { value: 'gms_vie', label: 'GMS VIE' },
    { value: 'gobert_assurances', label: 'GOBERT ASSURANCES' },
    { value: 'godefroy_assurances', label: 'GODEFROY ASSURANCES' },
    { value: 'gonthier_assurances', label: 'GONTHIER ASSURANCES' },
    { value: 'good_value_for_money', label: 'GOOD VALUE FOR MONEY' },
    { value: 'gordon_assurances', label: 'GORDON ASSURANCES' },
    { value: 'gorge_assurances', label: 'GORGE ASSURANCES' },
    { value: 'gourmand_assurances', label: 'GOURMAND ASSURANCES' },
    { value: 'gournay_assurances', label: 'GOURNAY ASSURANCES' },
    { value: 'gouttenoire_assurances', label: 'GOUTTENOIRE ASSURANCES' },
    { value: 'gp_prevoyance', label: 'GP PREVOYANCE' },
    { value: 'gp_sante', label: 'GP SANTE' },
    { value: 'gp_vie', label: 'GP VIE' },
    { value: 'grande_armee_assurances', label: 'GRANDE ARMEE ASSURANCES' },
    { value: 'gras_savoye', label: 'GRAS SAVOYE' },
    { value: 'gras_savoye_iard', label: 'GRAS SAVOYE IARD' },
    { value: 'gras_savoye_prevoyance', label: 'GRAS SAVOYE PREVOYANCE' },
    { value: 'gras_savoye_vie', label: 'GRAS SAVOYE VIE' },
    { value: 'gravia', label: 'GRAVIA' },
    { value: 'groupe_agricole', label: 'GROUPE AGRICOLE' },
    { value: 'groupe_agricole_prevoyance', label: 'GROUPE AGRICOLE PREVOYANCE' },
    { value: 'groupe_agricole_sante', label: 'GROUPE AGRICOLE SANTE' },
    { value: 'groupe_agricole_vie', label: 'GROUPE AGRICOLE VIE' },
    { value: 'groupe_allianz', label: 'GROUPE ALLIANZ' },
    { value: 'groupe_allsecur', label: 'GROUPE ALLSECUR' },
    { value: 'groupe_aviva', label: 'GROUPE AVIVA' },
    { value: 'groupe_covea', label: 'GROUPE COVEA' },
    { value: 'groupe_credit_agricole', label: 'GROUPE CREDIT AGRICOLE' },
    { value: 'groupe_credit_mutuel', label: 'GROUPE CREDIT MUTUEL' },
    { value: 'groupe_dassault', label: 'GROUPE DASSAULT' },
    { value: 'groupe_generali', label: 'GROUPE GENERALI' },
    { value: 'groupe_groupama', label: 'GROUPE GROUPAMA' },
    { value: 'groupe_macif', label: 'GROUPE MACIF' },
    { value: 'groupe_malakoff', label: 'GROUPE MALAKOFF' },
    { value: 'groupe_matmut', label: 'GROUPE MATMUT' },
    { value: 'groupe_mazars', label: 'GROUPE MAZARS' },
    { value: 'groupe_mutuelle_france', label: 'GROUPE MUTUELLE DE FRANCE' },
    { value: 'groupe_muta_sante', label: 'GROUPE MUTA SANTE' },
    { value: 'groupe_pasteur', label: 'GROUPE PASTEUR' },
    { value: 'groupe_pasteur_mutualite', label: 'GROUPE PASTEUR MUTUALITE' },
    { value: 'groupe_roederer', label: 'GROUPE ROEDERER' },
    { value: 'groupe_sma', label: 'GROUPE SMA' },
    { value: 'groupe_sogecap', label: 'GROUPE SOGECAP' },
    { value: 'groupe_sogessur', label: 'GROUPE SOGESSUR' },
    { value: 'groupe_vyv', label: 'GROUPE VYV' },
    { value: 'groupama', label: 'GROUPAMA' },
    { value: 'groupama_epargne', label: 'GROUPAMA EPARGNE' },
    { value: 'groupama_gan', label: 'GROUPAMA GAN' },
    { value: 'groupama_iard', label: 'GROUPAMA IARD' },
    { value: 'groupama_prevoyance', label: 'GROUPAMA PREVOYANCE' },
    { value: 'groupama_sante', label: 'GROUPAMA SANTE' },
    { value: 'groupama_vie', label: 'GROUPAMA VIE' },
    { value: 'groupavie', label: 'GROUPAVIE' },
    { value: 'groupavie_vie', label: 'GROUPAVIE VIE' },
    { value: 'groupmutuel', label: 'GROUPMUTUEL' },
    { value: 'gru', label: 'GRU' },
    { value: 'gsa_assurances', label: 'GSA ASSURANCES' },
    { value: 'guelle_assurances', label: 'GUELLE ASSURANCES' },
    { value: 'guerin_assurances', label: 'GUERIN ASSURANCES' },
    { value: 'guyot_assurances', label: 'GUYOT ASSURANCES' },
    { value: 'harmonie', label: 'HARMONIE' },
    { value: 'harmonie_epargne', label: 'HARMONIE EPARGNE' },
    { value: 'harmonie_epargne_retraite', label: 'HARMONIE EPARGNE RETRAITE' },
    { value: 'harmonie_fonction_publique', label: 'HARMONIE FONCTION PUBLIQUE' },
    { value: 'harmonie_iard', label: 'HARMONIE IARD' },
    { value: 'harmonie_mutuelle', label: 'HARMONIE MUTUELLE' },
    { value: 'harmonie_prevoyance', label: 'HARMONIE PREVOYANCE' },
    { value: 'harmonie_sante', label: 'HARMONIE SANTE' },
    { value: 'harmonie_vie', label: 'HARMONIE VIE' },
    { value: 'harmonieep', label: 'HARMONIEEP' },
    { value: 'helium_assurances', label: 'HELIUM ASSURANCES' },
    { value: 'helvetia', label: 'HELVETIA' },
    { value: 'helvetia_assurances', label: 'HELVETIA ASSURANCES' },
    { value: 'helvetia_vie', label: 'HELVETIA VIE' },
    { value: 'helvi', label: 'HELVI' },
    { value: 'henner', label: 'HENNER' },
    { value: 'henner_prevoyance', label: 'HENNER PREVOYANCE' },
    { value: 'henner_sante', label: 'HENNER SANTE' },
    { value: 'henner_vie', label: 'HENNER VIE' },
    { value: 'heracles_assurances', label: 'HERACLES ASSURANCES' },
    { value: 'hermitage_assurances', label: 'HERMITAGE ASSURANCES' },
    { value: 'hersant_assurances', label: 'HERSANT ASSURANCES' },
    { value: 'heyraud_assurances', label: 'HEYRAUD ASSURANCES' },
    { value: 'hoche_assurances', label: 'HOCHE ASSURANCES' },
    { value: 'hoche_iard', label: 'HOCHE IARD' },
    { value: 'hoche_vie', label: 'HOCHE VIE' },
    { value: 'hoffman_assurances', label: 'HOFFMAN ASSURANCES' },
    { value: 'homnia', label: 'HOMNIA' },
    { value: 'homnia_epargne', label: 'HOMNIA EPARGNE' },
    { value: 'homnia_prevoyance', label: 'HOMNIA PREVOYANCE' },
    { value: 'homnia_sante', label: 'HOMNIA SANTE' },
    { value: 'homnia_vie', label: 'HOMNIA VIE' },
    { value: 'horus', label: 'HORUS' },
    { value: 'hsbc_assurances', label: 'HSBC ASSURANCES' },
    { value: 'hsbc_iard', label: 'HSBC IARD' },
    { value: 'hsbc_prevoyance', label: 'HSBC PREVOYANCE' },
    { value: 'hsbc_vie', label: 'HSBC VIE' },
    { value: 'humanis', label: 'HUMANIS' },
    { value: 'humanis_epargne', label: 'HUMANIS EPARGNE' },
    { value: 'humanis_epargne_retraite', label: 'HUMANIS EPARGNE RETRAITE' },
    { value: 'humanis_iard', label: 'HUMANIS IARD' },
    { value: 'humanis_prevoyance', label: 'HUMANIS PREVOYANCE' },
    { value: 'humanis_sante', label: 'HUMANIS SANTE' },
    { value: 'humanis_vie', label: 'HUMANIS VIE' },
    { value: 'hydra_assurances', label: 'HYDRA ASSURANCES' },
    { value: 'iard', label: 'IARD' },
    { value: 'iardcollect', label: 'IARDCOLLECT' },
    { value: 'iardvie', label: 'IARDVIE' },
    { value: 'iardvie_sante', label: 'IARDVIE SANTE' },
    { value: 'iardvie_vie', label: 'IARDVIE VIE' },
    { value: 'ias_prevoyance', label: 'IAS PREVOYANCE' },
    { value: 'ias_sante', label: 'IAS SANTE' },
    { value: 'ias_vie', label: 'IAS VIE' },
    { value: 'icare', label: 'ICARE' },
    { value: 'icf', label: 'ICF' },
    { value: 'icf_prevoyance', label: 'ICF PREVOYANCE' },
    { value: 'icf_sante', label: 'ICF SANTE' },
    { value: 'icf_vie', label: 'ICF VIE' },
    { value: 'idealprevoyance', label: 'IDEALPREVOYANCE' },
    { value: 'identites_assurances', label: 'IDENTITES ASSURANCES' },
    { value: 'idprevoyance', label: 'IDPREVOYANCE' },
    { value: 'ifpass', label: 'IFPASS' },
    { value: 'igep', label: 'IGEP' },
    { value: 'igep_prevoyance', label: 'IGEP PREVOYANCE' },
    { value: 'igep_sante', label: 'IGEP SANTE' },
    { value: 'igep_vie', label: 'IGEP VIE' },
    { value: 'igesa', label: 'IGESA' },
    { value: 'illiade_assurances', label: 'ILLIADE ASSURANCES' },
    { value: 'imhotep', label: 'IMHOTEP' },
    { value: 'imhotep_sante', label: 'IMHOTEP SANTE' },
    { value: 'imhotep_vie', label: 'IMHOTEP VIE' },
    { value: 'immassur', label: 'IMMASSUR' },
    { value: 'immassur_vie', label: 'IMMASSUR VIE' },
    { value: 'immo_assurances', label: 'IMMO ASSURANCES' },
    { value: 'immo_prevoyance', label: 'IMMO PREVOYANCE' },
    { value: 'immo_sante', label: 'IMMO SANTE' },
    { value: 'immo_vie', label: 'IMMO VIE' },
    { value: 'imsa', label: 'IMSA' },
    { value: 'in_sante', label: 'IN SANTE' },
    { value: 'in_sante_prevoyance', label: 'IN SANTE PREVOYANCE' },
    { value: 'in_sante_vie', label: 'IN SANTE VIE' },
    { value: 'inadprevoyance', label: 'INADPREVOYANCE' },
    { value: 'inadprevoyance_vie', label: 'INADPREVOYANCE VIE' },
    { value: 'inavie', label: 'INAVIE' },
    { value: 'inaya', label: 'INAYA' },
    { value: 'inaya_sante', label: 'INAYA SANTE' },
    { value: 'inaya_vie', label: 'INAYA VIE' },
    { value: 'incendie_accidents', label: 'INCENDIE ACCIDENTS' },
    { value: 'indigo', label: 'INDIGO' },
    { value: 'indigo_assurances', label: 'INDIGO ASSURANCES' },
    { value: 'inextenso', label: 'INEXTENSO' },
    { value: 'innova', label: 'INNOVA' },
    { value: 'innova_sante', label: 'INNOVA SANTE' },
    { value: 'innova_vie', label: 'INNOVA VIE' },
    { value: 'inovassur', label: 'INOVASSUR' },
    { value: 'inovia', label: 'INOVIA' },
    { value: 'insassur', label: 'INSASSUR' },
    { value: 'insassur_prevoyance', label: 'INSASSUR PREVOYANCE' },
    { value: 'insassur_sante', label: 'INSASSUR SANTE' },
    { value: 'insassur_vie', label: 'INSASSUR VIE' },
    { value: 'insor_assurances', label: 'INSOR ASSURANCES' },
    { value: 'insurance_partner', label: 'INSURANCE PARTNER' },
    { value: 'insurancepartner_vie', label: 'INSURANCEPARTNER VIE' },
    { value: 'insurancevie', label: 'INSURANCEVIE' },
    { value: 'inter_partner_assistance', label: 'INTER PARTNER ASSISTANCE' },
    { value: 'interial', label: 'INTERIAL' },
    { value: 'interiale', label: 'INTERIALE' },
    { value: 'interiale_epargne', label: 'INTERIALE EPARGNE' },
    { value: 'interiale_prevoyance', label: 'INTERIALE PREVOYANCE' },
    { value: 'interiale_sante', label: 'INTERIALE SANTE' },
    { value: 'interiale_vie', label: 'INTERIALE VIE' },
    { value: 'intermutuelle', label: 'INTERMUTUELLE' },
    { value: 'internationale_assurances', label: 'INTERNATIONALE ASSURANCES' },
    { value: 'internationale_prevoyance', label: 'INTERNATIONALE DE PREVOYANCE' },
    { value: 'internationale_sante', label: 'INTERNATIONALE SANTE' },
    { value: 'internationale_vie', label: 'INTERNATIONALE VIE' },
    { value: 'intervie', label: 'INTERVIE' },
    { value: 'inthassur', label: 'INTHASSUR' },
    { value: 'inthassur_sante', label: 'INTHASSUR SANTE' },
    { value: 'inthassur_vie', label: 'INTHASSUR VIE' },
    { value: 'intrepide_assurances', label: 'INTREPIDE ASSURANCES' },
    { value: 'inviva', label: 'INVIVA' },
    { value: 'ionis', label: 'IONIS' },
    { value: 'ionis_prevoyance', label: 'IONIS PREVOYANCE' },
    { value: 'ionis_sante', label: 'IONIS SANTE' },
    { value: 'ionis_vie', label: 'IONIS VIE' },
    { value: 'ipac', label: 'IPAC' },
    { value: 'ipag', label: 'IPAG' },
    { value: 'ipag_sante', label: 'IPAG SANTE' },
    { value: 'ipag_vie', label: 'IPAG VIE' },
    { value: 'ipsec', label: 'IPSEC' },
    { value: 'irp_auto', label: 'IRP AUTO' },
    { value: 'irp_auto_prevoyance', label: 'IRP AUTO PREVOYANCE' },
    { value: 'irp_auto_sante', label: 'IRP AUTO SANTE' },
    { value: 'irp_auto_vie', label: 'IRP AUTO VIE' },
    { value: 'isante', label: 'ISANTE' },
    { value: 'isante_prevoyance', label: 'ISANTE PREVOYANCE' },
    { value: 'isante_vie', label: 'ISANTE VIE' },
    { value: 'isos', label: 'ISOS' },
    { value: 'isos_prevoyance', label: 'ISOS PREVOYANCE' },
    { value: 'isos_sante', label: 'ISOS SANTE' },
    { value: 'isos_vie', label: 'ISOS VIE' },
    { value: 'issy_assurances', label: 'ISSY ASSURANCES' },
    { value: 'itaassur', label: 'ITAASSUR' },
    { value: 'itaassur_vie', label: 'ITAASSUR VIE' },
    { value: 'itelis', label: 'ITELIS' },
    { value: 'itl_assurances', label: 'ITL ASSURANCES' },
    { value: 'itl_prevoyance', label: 'ITL PREVOYANCE' },
    { value: 'itl_sante', label: 'ITL SANTE' },
    { value: 'itl_vie', label: 'ITL VIE' },
    { value: 'iveco_assurances', label: 'IVECO ASSURANCES' },
    { value: 'ivs_assurances', label: 'IVS ASSURANCES' },
    { value: 'ivs_prevoyance', label: 'IVS PREVOYANCE' },
    { value: 'ivs_sante', label: 'IVS SANTE' },
    { value: 'ivs_vie', label: 'IVS VIE' },
    { value: 'zephir', label: 'ZEPHIR' },
    { value: 'oyat_assurances', label: 'OYAT ASSURANCES' },
    { value: 'solly_azar', label: 'Solly Azar' },
    { value: 'netvox', label: 'Netvox' },
    { value: 'cmam', label: 'CMAM' },
    { value: 'jl_assur', label: 'JLAssur' },
    { value: 'tetris', label: 'Tetris' },
    { value: 'orus', label: 'Orus' },
    { value: 'sada', label: 'Sada' },
    { value: 'zephir', label: 'Zephir' },
    { value: 'assurea', label: 'Assurea' },
    { value: 'malj', label: 'Malj' },
    { value: 'ami3f', label: 'Ami3f' },
    { value: 'leader', label: 'Leader' },
    { value: 'assurmax', label: 'Assurmax' },
    { value: 'xenassur', label: 'Xenassur' },
    { value: 'mila', label: 'Mila' }
  ];

  export const RISQUES = [
    { value: 'risque_2_roues', label: '2-Roues' },
    { value: 'assurance_recoltes', label: 'Assurance récoltes' },
    { value: 'assurance_tous_risques_chantier', label: 'Assurance tous risques chantier' },
    { value: 'assurance_trottinette', label: 'Assurance trottinette' },
    { value: 'assurance_velo', label: 'Assurance vélo' },
    { value: 'assurance_vie', label: 'Assurance Vie' },
    { value: 'assuraxi', label: 'Assuraxi' },
    { value: 'assurospi', label: 'Assurospi' },
    { value: 'auto', label: 'Auto' },
    { value: 'auto_pro', label: 'Auto Pro' },
    { value: 'autre', label: 'Autre' },
    { value: 'bateaux', label: 'Bateaux' },
    { value: 'bris_de_machine', label: 'Bris de machine' },
    { value: 'camping_car', label: 'Camping-car' },
    { value: 'caravanes', label: 'Caravanes' },
    { value: 'constructeur_non_realisateur', label: 'Constructeur non réalisateur' },
    { value: 'credit', label: 'Crédit' },
    { value: 'cyber_risques', label: 'Cyber risques' },
    { value: 'decennale_cdt', label: 'DECENNALE CDT' },
    { value: 'deces', label: 'Décès' },
    { value: 'defiscalisation', label: 'Défiscalisation' },
    { value: 'dependance', label: 'Dépendance' },
    { value: 'dommages_ouvrage', label: 'Dommages Ouvrage' },
    { value: 'emprunteur', label: 'Emprunteur' },
    { value: 'engin_de_chantier', label: 'Engin de chantier' },
    { value: 'flottes_auto', label: 'Flottes Auto' },
    { value: 'frais_d_obseques', label: 'Frais d\'obsèques' },
    { value: 'frais_generaux', label: 'Frais Généraux' },
    { value: 'garantie_financiere_achevement', label: 'Garantie financière d\'achèvement' },
    { value: 'gav', label: 'GAV' },
    { value: 'gsc', label: 'GSC' },
    { value: 'homme_cle', label: 'Homme Clé' },
    { value: 'ifc', label: 'IFC' },
    { value: 'immeuble', label: 'Immeuble' },
    { value: 'indemnite_journaliere_hospitaliere', label: 'Indemnité Journalière Hospitalière' },
    { value: 'investissement_immobilier', label: 'Investissement immobilier' },
    { value: 'jetski', label: 'Jetski' },
    { value: 'loyer_impaye_risque_locatif', label: 'Loyer impayé / Risque locatif' },
    { value: 'marchandises_transportees', label: 'Marchandises transportées' },
    { value: 'mrh', label: 'MRH' },
    { value: 'mrpro', label: 'MRPro' },
    { value: 'mrpro_de_l_auto', label: 'MRPro de l\'auto' },
    { value: 'objets_d_art_et_collections', label: 'Objets d\'art et collections' },
    { value: 'obseques', label: 'Obsèques' },
    { value: 'pee', label: 'PEE' },
    { value: 'per', label: 'PER' },
    { value: 'perco', label: 'PERCO' },
    { value: 'perp', label: 'PERP' },
    { value: 'perte_d_exploitation', label: 'Perte d\'exploitation' },
    { value: 'plaisance', label: 'Plaisance' },
    { value: 'pno', label: 'PNO' },
    { value: 'prevoyance_collective', label: 'Prévoyance Collective' },
    { value: 'prevoyance_individuelle', label: 'Prévoyance individuelle' },
    { value: 'prevoyance_tns', label: 'Prévoyance TNS' },
    { value: 'protection_juridique', label: 'Protection juridique' },
    { value: 'protection_juridique_pro', label: 'Protection juridique pro' },
    { value: 'quad', label: 'QUAD' },
    { value: 'rachat_de_franchise', label: 'Rachat de franchise' },
    { value: 'rc_chasse', label: 'RC Chasse' },
    { value: 'rc_decennale', label: 'RC Décennale' },
    { value: 'rc_environnement', label: 'RC environnement' },
    { value: 'rc_medicale', label: 'RC Médicale' },
    { value: 'rc_navigation_aerienne', label: 'RC Navigation Aérienne' },
    { value: 'rc_organisation', label: 'RC organisation' },
    { value: 'rc_pro', label: 'RC Pro' },
    { value: 'rc_vie_privee', label: 'RC Vie Privée' },
    { value: 'remorque', label: 'Remorque' },
    { value: 'rente_education', label: 'Rente éducation' },
    { value: 'rente_viagere', label: 'Rente viagère' },
    { value: 'responsabilite_des_dirigeants', label: 'Responsabilité des dirigeants' },
    { value: 'retraite_83', label: 'Retraite 83' },
    { value: 'retraite_madelin', label: 'Retraite Madelin' },
    { value: 'sante_actifs', label: 'Santé Actifs' },
    { value: 'sante_animale', label: 'Santé Animale' },
    { value: 'sante_collective', label: 'Santé Collective' },
    { value: 'sante_individuelle', label: 'Santé individuelle' },
    { value: 'sante_seniors', label: 'Santé Séniors' },
    { value: 'sante_tns', label: 'Santé TNS' },
    { value: 'scolaire', label: 'Scolaire' },
    { value: 'surcomplementaire', label: 'Surcomplémentaire' },
    { value: 'tous_risques_chantier', label: 'Tous risques chantier' },
    { value: 'voiture_sans_permis_voiturette', label: 'VoituresansPermis/Voiturette' },
    { value: 'voyage', label: 'Voyage' }
  ];